[language-server.eslint]
args = ["--stdio"]
command = "vscode-eslint-language-server"

[language-server.eslint.config]
format = true
nodePath = ""
onIgnoredFiles = "off"
packageManager = "yarn"
quiet = false
rulesCustomizations = []
run = "onType"
useESLintClass = false
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
codeActionOnSave = { mode = "all" }
experimental = { }
problems = { shortenToSingleLine = false }
workingDirectory = { mode = "auto" }

[[language]]
name = "typescript"
file-types = ["ts", "tsx"]
language-servers = ["typescript-language-server", "eslint"]
formatter = { command = "npx", args = [ "prettier", "--parser", "typescript" ] }
auto-format = true
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "javascript"
file-types = ["js", "jsx"]
language-servers = ["typescript-language-server", "eslint"]
formatter = { command = "npx", args = [ "prettier", "--parser", "typescript" ] }
auto-format = true
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "rust"
auto-format = false
